/***************************************************************/
/* Copyright (c) 2016 Andrej Borovski [andrej.borovski@mail.com]

This file is part of FastSecret.

FastSecret is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/> */
/*********************************************************************/
package fsgui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.TextArea;
import java.awt.dnd.DropTarget;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Andrej Borovski
 */
public class DropFrame extends javax.swing.JFrame {

    /** Creates new form DropFrame */
    public DropFrame() {
        initComponents();
        setLayout(new BorderLayout());
        JPanel panel = new JPanel();
        AddFilePanel afp = new AddFilePanel();
        panel.add(afp, null);
        afp.setEnabled(true);
        setDropTarget(new DropTarget(afp, new DropListener(afp, afp)));
        afp.setToolTipText("Drop files here");
        
        //setLayout(new BorderLayout());
       // JPanel panel = new JPanel();
        add(panel, BorderLayout.CENTER);
        DropPane dp = new DropPane();
        BoxLayout boxLayout = new BoxLayout(panel, BoxLayout.X_AXIS);
        panel.setLayout(boxLayout);
        panel.add(dp);
        panel.setEnabled(true);
        panel.setVisible(true);
        dp.setVisible(true);
        dp.setToolTipText("Drop text fragments and URLs here");
        
      TextArea tp = new TextArea();
        panel.add(tp, null);
        tp.setEnabled(true);
       // setDropTarget(new DropTarget(afp, new DropListener(afp, afp)));
        
        panel.revalidate();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("FastSecret");
        setAlwaysOnTop(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
