/**
 * ************************************************************
 */
/* Copyright (c) 2016 Andrej Borovski [andrej.borovski@mail.com]

This file is part of FastSecret.

FastSecret is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/> */
/**
 * ******************************************************************
 */
package fsgui;

import fscore.Storage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author artem
 */
public class EnterPasswordPanel extends javax.swing.JPanel { 
    class EnterPasswordListener implements ActionListener
    {
        ListSelectionListener listener;
        ListSelectionEvent event;
        @Override
        public void actionPerformed(ActionEvent e) {
            Storage.INSTANCE.closeFileReader();
            Storage.INSTANCE.openFileReader(Storage.INSTANCE.getFileName(), new String(jPasswordField23.getPassword()));
            if (Storage.INSTANCE.canDecrypt()) {
                if (CommonComponents.SELECT.recordTableModel.getRowCount() != 0)
                    listener.valueChanged(event);
                else
                    CommonComponents.SELECT.showEncryptTutorPanel();
            } else {
                CommonComponents.SELECT.getPanel().removeAll();
                JOptionPane.showMessageDialog(CommonComponents.SELECT.getPanel(), "Wrong password", "Input Error", JOptionPane.ERROR_MESSAGE, CommonComponents.createImageIcon(CommonComponents.EXCLAMATION));
                CommonComponents.SELECT.tableSelectionListener.showEnterPasswordPanel();
            }
        }
        public void addSelectionListener(ListSelectionListener l, ListSelectionEvent e) {
            listener = l;
            event = e;
        }
        
    }
    
  /*  class PasswordLineListener implements KeyListener
    {

        @Override
        public void keyTyped(KeyEvent e) {
            
        }

        @Override
        public void keyPressed(KeyEvent e) {
            jPasswordField23.setText("");
            jPasswordField23.removeKeyListener(pll);
        }

        @Override
        public void keyReleased(KeyEvent e) {
            
        }
        
    }*/
    
    
    
    EnterPasswordListener epl;
    
    /**
     * Creates new form EnterPasswordPanel
     */
    public EnterPasswordPanel() {
        initComponents();
        epl = new EnterPasswordListener();
        jPasswordField23.addFocusListener(new TextLineCleaner());
        jPasswordField23.addActionListener(epl);
        jPasswordField23.requestFocusInWindow();
        
    }

    public void setFocus()
    {
        jPasswordField23.requestFocusInWindow();
    }
    
    public void AddSelectionListener(ListSelectionListener l, ListSelectionEvent e)
    {
        epl.addSelectionListener(l, e);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField23 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField23.setText("jPasswordField1");
        jPasswordField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField23ActionPerformed(evt);
            }
        });

        jLabel1.setText("To view the content enter the password please");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock_lock_open.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock_lock.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField23, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField23;
    // End of variables declaration//GEN-END:variables
}
