/**
 * ************************************************************
 */
/* Copyright (c) 2016 Andrej Borovski [andrej.borovski@mail.com]

This file is part of FastSecret.

FastSecret is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/> */
/**
 * ******************************************************************
 */
package fsgui;

import fscore.RecordInfo;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;


/**
 *
 * @author artem
 */
public class NewFormDialog extends javax.swing.JDialog {
    RecordInfo ri;
    FormPanel fp;
    /**
     * Creates new form NewFormDialog
     */
    public NewFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ri = new RecordInfo();
        fp = new FormPanel(false);
        jPanel1.setVisible(true);
        jPanel1.add(fp);
        fp.setVisible(true);
        this.addComponentListener(new ComponentListener() {
            @Override
            public void componentResized(ComponentEvent e) {
            }

            @Override
            public void componentMoved(ComponentEvent e) {
            }

            @Override
            public void componentShown(ComponentEvent e) {
            }

            @Override
            public void componentHidden(ComponentEvent e) {
               CommonComponents.SELECT.clearDropPane();
            }
 });
    }

    public String getRecordTitle()
    {
        return fp.getTitle().isEmpty() ? "New Record" : fp.getTitle();
    }
  
    public String getURL()
    {
        return fp.getURL();
    }
    
    public void setURL(String url)
    {
        fp.setURL(url);
    }
    
    public String getLogin()
    {
        return fp.getLogin();
    }
    
    public String getPasswod()
    {
        return fp.getPassword();
    }
    
    public String getNote()
    {
        return fp.getNote();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setTitle("New Record");
        setMinimumSize(new java.awt.Dimension(486, 300));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
